[settings]
disable_tools = ['python']
experimental = true
not_found_auto_install = false
idiomatic_version_file_enable_tools = ["[]"]

[tools]
bun = ['latest']
go = ['latest']
node = ['22', '24', 'latest']
ruby = ['latest']
rust = ['latest']
usage = ['latest']  # Required for mise shell completions

[tasks.bootstrap]
description = "Bootstrap our CLI"
run = "mise upgrade"
